# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWCHtD48GjVF1e6iD9elQhDA_IpaKfd_
"""

# ============================================================
# SETUP — run this once. Rebuilds the coffee_agent package on disk.
# ============================================================
!pip install -q "pydantic>=2" transformers torch --quiet

import os
from pathlib import Path

ROOT = Path("/content/coffee_agent_project")
PKG = ROOT / "coffee_agent"
for sub in ["", "data", "tools", "llm", "agent"]:
    (PKG / sub).mkdir(parents=True, exist_ok=True)

def write(rel_path: str, content: str):
    p = PKG / rel_path
    p.write_text(content)

# ---------------- __init__.py files ----------------
write("__init__.py", '''
from coffee_agent.agent import CoffeeAgent
from coffee_agent.schemas import AgentRequest, AgentResponse

__all__ = ["CoffeeAgent", "AgentRequest", "AgentResponse"]
''')
write("data/__init__.py", "")
write("tools/__init__.py", "")

# ---------------- config.py (reconstructed) ----------------
write("config.py", '''
from __future__ import annotations
import os
from dataclasses import dataclass


@dataclass(frozen=True)
class Settings:
    llm_backend: str = "rule_based"  # "rule_based" | "local" | "auto"
    local_model_name: str = "google/flan-t5-base"
    unresolved_item_fallback_time_min: float = 2.5
    default_prep_buffer_min: float = 1.0


def get_settings() -> Settings:
    return Settings(
        llm_backend=os.environ.get("COFFEE_AGENT_LLM_BACKEND", "rule_based"),
        local_model_name=os.environ.get("COFFEE_AGENT_LOCAL_MODEL", "google/flan-t5-base"),
    )
''')

# ---------------- schemas.py (as uploaded) ----------------
write("schemas.py", '''
from __future__ import annotations

import time
from enum import Enum

from pydantic import BaseModel, Field


class Intent(str, Enum):
    EXACT_MENU = "exact_menu"
    COMPLEX_ORDER = "complex_order"
    PREFERENCE = "preference"
    RECOMMENDATION = "recommendation"


class Category(str, Enum):
    COFFEE = "coffee"
    TEA = "tea"
    COLD = "cold"
    SWEET = "sweet"
    FOOD = "food"


class MenuItem(BaseModel):
    name: str
    base_time_min: float = Field(gt=0)
    category: Category
    tags: list[str] = Field(default_factory=list)
    price_inr: float = Field(gt=0)
    calories: int = Field(gt=0)


class Modifier(BaseModel):
    name: str
    is_multiplier: bool
    time_effect: float
    price_delta_inr: float = 0.0


class ResolvedLineItem(BaseModel):
    name: str
    quantity: int = 1
    modifiers: list[str] = Field(default_factory=list)
    unit_time_min: float
    line_time_min: float
    unit_price_inr: float
    line_price_inr: float
    source: str


class TraceStep(BaseModel):
    step: str
    detail: str
    tool: str
    elapsed_ms: float = 0.0
    timestamp: float = Field(default_factory=time.time)


class AgentRequest(BaseModel):
    text: str = Field(min_length=1, max_length=500)


class AgentResponse(BaseModel):
    request_text: str
    intent: Intent
    items: list[ResolvedLineItem]
    total_time_min: float
    total_price_inr: float
    method: str
    confidence: float = Field(ge=0.0, le=1.0)
    trace: list[TraceStep]

    @property
    def recommendation_summary(self) -> str:
        return ", ".join(f"{i.quantity}x {i.name.title()}" for i in self.items)
''')

# ---------------- data/menu.py (as uploaded) ----------------
write("data/menu.py", '''
from __future__ import annotations

from coffee_agent.schemas import Category, MenuItem, Modifier

_RAW_MENU: list[MenuItem] = [
    MenuItem(name="espresso", base_time_min=1.5, category=Category.COFFEE,
              tags=["strong", "quick", "high-caffeine", "black"], price_inr=90, calories=5),
    MenuItem(name="americano", base_time_min=2.0, category=Category.COFFEE,
              tags=["strong", "black", "high-caffeine"], price_inr=110, calories=10),
    MenuItem(name="double espresso", base_time_min=2.2, category=Category.COFFEE,
              tags=["very-strong", "quick", "high-caffeine"], price_inr=130, calories=10),
    MenuItem(name="latte", base_time_min=3.0, category=Category.COFFEE,
              tags=["milky", "mild", "sweet-possible"], price_inr=160, calories=190),
    MenuItem(name="cappuccino", base_time_min=3.0, category=Category.COFFEE,
              tags=["milky", "foamy"], price_inr=150, calories=120),
    MenuItem(name="mocha", base_time_min=3.5, category=Category.COFFEE,
              tags=["sweet", "chocolate", "celebratory"], price_inr=180, calories=290),
    MenuItem(name="flat white", base_time_min=3.0, category=Category.COFFEE,
              tags=["milky", "smooth"], price_inr=170, calories=170),
    MenuItem(name="cold brew", base_time_min=1.0, category=Category.COLD,
              tags=["cold", "strong", "smooth"], price_inr=170, calories=5),
    MenuItem(name="iced coffee", base_time_min=1.5, category=Category.COLD,
              tags=["cold", "refreshing"], price_inr=150, calories=110),
    MenuItem(name="matcha", base_time_min=3.0, category=Category.TEA,
              tags=["healthy", "green", "antioxidant"], price_inr=190, calories=80),
    MenuItem(name="green tea", base_time_min=2.0, category=Category.TEA,
              tags=["healthy", "light", "low-caffeine"], price_inr=90, calories=2),
    MenuItem(name="black tea", base_time_min=2.0, category=Category.TEA,
              tags=["healthy", "black"], price_inr=90, calories=2),
    MenuItem(name="hot chocolate", base_time_min=2.5, category=Category.SWEET,
              tags=["sweet", "comfort"], price_inr=160, calories=320),
    MenuItem(name="smoothie", base_time_min=4.0, category=Category.COLD,
              tags=["cold", "sweet", "healthy-option"], price_inr=180, calories=210),
    MenuItem(name="croissant", base_time_min=0.5, category=Category.FOOD,
              tags=["food", "pastry"], price_inr=110, calories=270),
    MenuItem(name="bagel", base_time_min=1.5, category=Category.FOOD,
              tags=["food"], price_inr=100, calories=250),
    MenuItem(name="sandwich", base_time_min=4.0, category=Category.FOOD,
              tags=["food", "filling"], price_inr=190, calories=350),
]

_RAW_MODIFIERS: list[Modifier] = [
    Modifier(name="extra large", is_multiplier=True, time_effect=1.4, price_delta_inr=60),
    Modifier(name="xl", is_multiplier=True, time_effect=1.4, price_delta_inr=60),
    Modifier(name="large", is_multiplier=True, time_effect=1.2, price_delta_inr=35),
    Modifier(name="double", is_multiplier=True, time_effect=1.5, price_delta_inr=70),
    Modifier(name="oat milk", is_multiplier=False, time_effect=0.3, price_delta_inr=30),
    Modifier(name="almond milk", is_multiplier=False, time_effect=0.3, price_delta_inr=30),
    Modifier(name="soy milk", is_multiplier=False, time_effect=0.3, price_delta_inr=25),
    Modifier(name="extra hot", is_multiplier=False, time_effect=0.5, price_delta_inr=0),
    Modifier(name="toasted", is_multiplier=False, time_effect=0.5, price_delta_inr=0),
    Modifier(name="vanilla", is_multiplier=False, time_effect=0.2, price_delta_inr=20),
    Modifier(name="caramel", is_multiplier=False, time_effect=0.3, price_delta_inr=25),
    Modifier(name="whipped cream", is_multiplier=False, time_effect=0.4, price_delta_inr=30),
    Modifier(name="extra shot", is_multiplier=False, time_effect=0.8, price_delta_inr=40),
]

_RAW_MODIFIERS.sort(key=lambda m: len(m.name), reverse=True)


class MenuRepository:
    def __init__(self, items: list[MenuItem] | None = None,
                 modifiers: list[Modifier] | None = None) -> None:
        self._items = items if items is not None else _RAW_MENU
        self._modifiers = modifiers if modifiers is not None else _RAW_MODIFIERS
        self._items_by_specificity = sorted(self._items, key=lambda m: len(m.name), reverse=True)

    def all_items(self) -> list[MenuItem]:
        return list(self._items)

    def all_modifiers(self) -> list[Modifier]:
        return list(self._modifiers)

    def find_item_in_text(self, text: str) -> MenuItem | None:
        normalised = text.lower()
        for item in self._items_by_specificity:
            if item.name in normalised:
                return item
        return None

    def get_item(self, name: str) -> MenuItem | None:
        normalised = name.lower().strip()
        for item in self._items:
            if item.name == normalised:
                return item
        return None

    def find_modifiers_in_text(self, text: str) -> list[Modifier]:
        normalised = text.lower()
        found: list[Modifier] = []
        consumed = normalised
        for mod in self._modifiers:
            if mod.name in consumed:
                found.append(mod)
                consumed = consumed.replace(mod.name, " ", 1)
        return found

    def menu_names(self) -> list[str]:
        return [item.name for item in self._items]
''')

# ---------------- tools/order_parser.py (reconstructed) ----------------
write("tools/order_parser.py", '''
from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass
class ParsedLine:
    raw_text: str
    quantity: int = 1


_QUANTITY_RE = re.compile(r"^\\s*(\\d+)\\s*[xX]?\\s+")
_GROUP_SIZE_RE = re.compile(
    r"(?:for|table of|party of)\\s+(\\d+)\\s*(?:people|of us|guys|friends)?",
    re.IGNORECASE,
)
_SPLIT_RE = re.compile(r",|\\band\\b|\\bthen\\b|\\bplus\\b", re.IGNORECASE)


class OrderParser:
    """Splits raw order text into individual lines with quantities, and
    detects an overall group size (e.g. \"for 4 people\")."""

    def parse(self, text: str) -> tuple[list[ParsedLine], int]:
        group_size = 1
        match = _GROUP_SIZE_RE.search(text)
        if match:
            group_size = int(match.group(1))
            text = _GROUP_SIZE_RE.sub("", text)

        raw_lines = [p.strip() for p in _SPLIT_RE.split(text) if p.strip()]
        parsed: list[ParsedLine] = []
        for line in raw_lines:
            qty = 1
            m = _QUANTITY_RE.match(line)
            if m:
                qty = int(m.group(1))
                line = _QUANTITY_RE.sub("", line, count=1).strip()
            if line:
                parsed.append(ParsedLine(raw_text=line, quantity=qty))
        return parsed, group_size
''')

# ---------------- tools/dietary_filter.py (as uploaded) ----------------
write("tools/dietary_filter.py", '''
from __future__ import annotations

from dataclasses import dataclass

from coffee_agent.data.menu import MenuRepository

_CONSTRAINT_RULES: dict[str, tuple[list[str], list[str]]] = {
    "lactose": (["milky", "foamy"], []),
    "dairy": (["milky", "foamy"], []),
    "vegan": (["milky", "foamy"], []),
    "healthiest": ([], ["healthy", "healthy-option"]),
    "healthy": ([], ["healthy", "healthy-option"]),
    "diet": ([], ["healthy", "healthy-option", "light"]),
    "low calorie": ([], ["healthy", "light"]),
    "low-caffeine": (["high-caffeine"], ["low-caffeine"]),
    "decaf": (["high-caffeine"], []),
    "no caffeine": (["high-caffeine"], []),
}


@dataclass(frozen=True)
class DietaryFilterResult:
    candidate_names: list[str]
    matched_constraints: list[str]


class DietaryFilter:
    def __init__(self, menu_repo: MenuRepository) -> None:
        self._menu = menu_repo

    def filter_candidates(self, text: str) -> DietaryFilterResult:
        normalised = text.lower()
        excluded_tags: set[str] = set()
        preferred_tags: set[str] = set()
        matched: list[str] = []

        for keyword, (excl, pref) in _CONSTRAINT_RULES.items():
            if keyword in normalised:
                excluded_tags.update(excl)
                preferred_tags.update(pref)
                matched.append(keyword)

        items = self._menu.all_items()
        if excluded_tags:
            items = [i for i in items if not excluded_tags.intersection(i.tags)]
        if preferred_tags:
            preferred_items = [i for i in items if preferred_tags.intersection(i.tags)]
            if preferred_items:
                items = preferred_items

        if not items:
            items = self._menu.all_items()

        return DietaryFilterResult(
            candidate_names=[i.name for i in items],
            matched_constraints=matched,
        )
''')

# ---------------- tools/estimator.py (as uploaded) ----------------
write("tools/estimator.py", '''
from __future__ import annotations

from coffee_agent.data.menu import MenuRepository
from coffee_agent.schemas import ResolvedLineItem
from coffee_agent.tools.order_parser import ParsedLine


class TimeEstimator:
    def __init__(self, menu_repo: MenuRepository) -> None:
        self._menu = menu_repo

    def resolve_from_menu(self, parsed: ParsedLine) -> ResolvedLineItem | None:
        item = self._menu.find_item_in_text(parsed.raw_text)
        if item is None:
            return None

        modifiers = self._menu.find_modifiers_in_text(parsed.raw_text)
        time_min = item.base_time_min
        price_inr = item.price_inr
        modifier_names: list[str] = []
        for mod in modifiers:
            time_min = time_min * mod.time_effect if mod.is_multiplier else time_min + mod.time_effect
            price_inr += mod.price_delta_inr
            modifier_names.append(mod.name)

        unit_time = round(time_min, 2)
        unit_price = round(price_inr, 2)
        return ResolvedLineItem(
            name=item.name,
            quantity=parsed.quantity,
            modifiers=modifier_names,
            unit_time_min=unit_time,
            line_time_min=round(unit_time * parsed.quantity, 2),
            unit_price_inr=unit_price,
            line_price_inr=round(unit_price * parsed.quantity, 2),
            source="menu_lookup",
        )

    def resolve_named_item(self, name: str, quantity: int, source: str,
                             fallback_time_min: float) -> ResolvedLineItem:
        item = self._menu.get_item(name.lower().strip())
        if item is not None:
            return ResolvedLineItem(
                name=item.name,
                quantity=quantity,
                modifiers=[],
                unit_time_min=item.base_time_min,
                line_time_min=round(item.base_time_min * quantity, 2),
                unit_price_inr=item.price_inr,
                line_price_inr=round(item.price_inr * quantity, 2),
                source=source,
            )
        return ResolvedLineItem(
            name=name.strip().lower() or "barista's choice",
            quantity=quantity,
            modifiers=[],
            unit_time_min=fallback_time_min,
            line_time_min=round(fallback_time_min * quantity, 2),
            unit_price_inr=0.0,
            line_price_inr=0.0,
            source="fallback",
        )
''')

# ---------------- llm/base.py (reconstructed) ----------------
write("llm/base.py", '''
from __future__ import annotations

from abc import ABC, abstractmethod


class LLMBackend(ABC):
    """Interface every recommendation backend must implement."""

    @property
    @abstractmethod
    def name(self) -> str: ...

    @abstractmethod
    def recommend_item(self, preference_text: str, candidate_items: list[str]) -> str: ...
''')

# ---------------- llm/rule_based_backend.py (as uploaded) ----------------
write("llm/rule_based_backend.py", '''
from __future__ import annotations

from coffee_agent.data.menu import MenuRepository
from coffee_agent.llm.base import LLMBackend

_KEYWORD_TAGS: dict[str, list[str]] = {
    "tired": ["high-caffeine", "strong"],
    "sleep": ["high-caffeine", "strong"],
    "meeting": ["quick", "high-caffeine"],
    "quick": ["quick"],
    "fast": ["quick"],
    "strong": ["strong", "high-caffeine"],
    "cold": ["cold"],
    "iced": ["cold"],
    "sweet": ["sweet"],
    "dessert": ["sweet"],
    "healthy": ["healthy", "healthy-option"],
    "diet": ["healthy", "healthy-option"],
    "birthday": ["celebratory", "sweet"],
    "celebrat": ["celebratory"],
    "lactose": ["black", "quick"],
    "vegan": ["black"],
    "relax": ["smooth", "mild"],
    "chill": ["smooth", "mild"],
}


class RuleBasedBackend(LLMBackend):
    def __init__(self, menu_repo: MenuRepository) -> None:
        self._menu = menu_repo

    @property
    def name(self) -> str:
        return "rule-based-tag-matcher"

    def recommend_item(self, preference_text: str, candidate_items: list[str]) -> str:
        text = preference_text.lower()
        wanted_tags: set[str] = set()
        for keyword, tags in _KEYWORD_TAGS.items():
            if keyword in text:
                wanted_tags.update(tags)

        items = [i for i in self._menu.all_items() if i.name in candidate_items] or self._menu.all_items()
        if not wanted_tags:
            preferred_default = next((i for i in items if i.name == "latte"), None)
            return preferred_default.name if preferred_default else items[0].name

        best_item = max(items, key=lambda i: len(wanted_tags.intersection(i.tags)))
        return best_item.name
''')

# ---------------- llm/local_backend.py (as uploaded) ----------------
write("llm/local_backend.py", '''
from __future__ import annotations

import logging
import re

from coffee_agent.llm.base import LLMBackend

logger = logging.getLogger("coffee_agent.llm.local")


class HFLocalBackend(LLMBackend):
    def __init__(self, model_name: str = "google/flan-t5-base",
                 max_new_tokens: int = 16, device: str = "cpu") -> None:
        self._model_name = model_name
        self._max_new_tokens = max_new_tokens
        self._device = device
        self._tokenizer = None
        self._model = None

    @property
    def name(self) -> str:
        return f"huggingface:{self._model_name}"

    def _ensure_loaded(self) -> None:
        if self._model is not None:
            return
        logger.info("Loading local model %s (first use, lazy)...", self._model_name)
        from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

        self._tokenizer = AutoTokenizer.from_pretrained(self._model_name)
        self._model = AutoModelForSeq2SeqLM.from_pretrained(self._model_name).to(self._device)
        logger.info("Model %s ready.", self._model_name)

    def _generate(self, prompt: str) -> str:
        self._ensure_loaded()
        inputs = self._tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(self._device)
        outputs = self._model.generate(**inputs, max_new_tokens=self._max_new_tokens, do_sample=False)
        return self._tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

    def recommend_item(self, preference_text: str, candidate_items: list[str]) -> str:
        # Local backend currently uses improved rule-based scoring logic
        # for precision, while supporting the _generate infrastructure.
        from coffee_agent.llm.rule_based_backend import _KEYWORD_TAGS
        text = preference_text.lower()
        wanted_tags: set[str] = set()
        for keyword, tags in _KEYWORD_TAGS.items():
            if keyword in text:
                wanted_tags.update(tags)

        from coffee_agent.data.menu import MenuRepository
        repo = MenuRepository()
        items = [i for i in repo.all_items() if i.name in candidate_items] or repo.all_items()

        if not wanted_tags:
            preferred_default = next((i for i in items if i.name == "latte"), None)
            return preferred_default.name if preferred_default else items[0].name

        def score(item):
            overlap = wanted_tags.intersection(item.tags)
            if not overlap:
                return 0.0
            return len(overlap) / len(set(item.tags) | wanted_tags)

        scored = [(score(i), i) for i in items]
        best_score = max(s for s, _ in scored)
        best_items = [i for s, i in scored if s == best_score]
        best_items.sort(key=lambda i: len(i.tags))
        return best_items[0].name

    @staticmethod
    def _best_menu_match(raw_output: str, candidate_items: list[str]) -> str:
        cleaned = re.sub(r"[^a-z\\s]", "", raw_output).strip()
        for item in sorted(candidate_items, key=len, reverse=True):
            if item in cleaned:
                return item
        return cleaned or (candidate_items[0] if candidate_items else "barista's choice")
''')

# ---------------- llm/__init__.py (reconstructed factory) ----------------
write("llm/__init__.py", '''
from __future__ import annotations

import logging

from coffee_agent.config import Settings
from coffee_agent.data.menu import MenuRepository
from coffee_agent.llm.base import LLMBackend
from coffee_agent.llm.rule_based_backend import RuleBasedBackend

logger = logging.getLogger("coffee_agent.llm")


def get_llm_backend(settings: Settings, menu_repo: MenuRepository) -> LLMBackend:
    if settings.llm_backend == "rule_based":
        return RuleBasedBackend(menu_repo)

    if settings.llm_backend in ("auto", "local"):
        try:
            from coffee_agent.llm.local_backend import HFLocalBackend
            return HFLocalBackend(model_name=settings.local_model_name)
        except Exception as e:
            logger.warning("Local model unavailable, falling back to rule-based: %s", e)
            if settings.llm_backend == "local":
                raise
            return RuleBasedBackend(menu_repo)

    return RuleBasedBackend(menu_repo)
''')

# ---------------- agent/intent.py (as uploaded) ----------------
write("agent/intent.py", r'''
from __future__ import annotations

from coffee_agent.data.menu import MenuRepository
from coffee_agent.schemas import Intent
from coffee_agent.tools.order_parser import OrderParser

_PREFERENCE_KEYWORDS = (
    "lactose", "dairy", "vegan", "allergic", "allergy", "gluten",
    "healthiest", "healthy option", "diet", "low calorie", "low-calorie",
    "decaf", "no caffeine", "low-caffeine", "sugar-free", "sugar free",
    "i don't like", "i dont like", "can't have", "cant have", "avoid",
)


class IntentClassifier:
    def __init__(self, menu_repo: MenuRepository, order_parser: OrderParser) -> None:
        self._menu = menu_repo
        self._parser = order_parser

    def classify(self, text: str) -> tuple[Intent, str]:
        normalised = text.lower().strip()
        lines, group_size = self._parser.parse(normalised)

        has_explicit_quantity = any(line.quantity > 1 for line in lines)
        matched_items = [self._menu.find_item_in_text(line.raw_text) for line in lines]
        known_item_count = sum(1 for item in matched_items if item is not None)

        if group_size > 1:
            return Intent.COMPLEX_ORDER, f"an explicit group size of {group_size} was detected"
        if has_explicit_quantity:
            return Intent.COMPLEX_ORDER, "an explicit item quantity (e.g. '2 lattes') was detected"
        if len(lines) >= 2 and known_item_count >= 2:
            return Intent.COMPLEX_ORDER, f"{known_item_count} distinct menu items were detected across {len(lines)} lines"

        has_preference_signal = any(kw in normalised for kw in _PREFERENCE_KEYWORDS)
        single_matched_item = matched_items[0] if matched_items else None

        if single_matched_item is not None and not has_preference_signal:
            return Intent.EXACT_MENU, f"'{single_matched_item.name}' matches a known menu item directly"

        if has_preference_signal:
            return Intent.PREFERENCE, "the request states a dietary/health constraint"

        return Intent.RECOMMENDATION, "no menu item or constraint was found - this is an open-ended ask"
''')

# ---------------- agent/__init__.py (the orchestrator) ----------------
write("agent/__init__.py", r'''
from __future__ import annotations

import logging
import time

from coffee_agent.config import Settings, get_settings
from coffee_agent.data.menu import MenuRepository
from coffee_agent.llm import get_llm_backend
from coffee_agent.llm.base import LLMBackend
from coffee_agent.schemas import AgentResponse, Intent, ResolvedLineItem, TraceStep
from coffee_agent.tools.dietary_filter import DietaryFilter
from coffee_agent.tools.estimator import TimeEstimator

from coffee_agent.tools.order_parser import OrderParser, ParsedLine
from coffee_agent.agent.intent import IntentClassifier

logger = logging.getLogger("coffee_agent.agent")


class CoffeeAgent:
    def __init__(
        self,
        settings: Settings | None = None,
        menu_repo: MenuRepository | None = None,
        llm_backend: LLMBackend | None = None,
    ) -> None:
        self.settings = settings or get_settings()
        self.menu = menu_repo or MenuRepository()
        self.parser = OrderParser()
        self.estimator = TimeEstimator(self.menu)
        self.dietary_filter = DietaryFilter(self.menu)
        self.intent_classifier = IntentClassifier(self.menu, self.parser)
        self.llm = llm_backend or get_llm_backend(self.settings, self.menu)
        logger.info("CoffeeAgent initialised with LLM backend: %s", self.llm.name)

    def handle(self, request_text: str) -> AgentResponse:
        request_text = request_text.strip()
        trace: list[TraceStep] = []

        t0 = time.perf_counter()
        intent, reason = self.intent_classifier.classify(request_text)
        trace.append(TraceStep(
            step="classify_intent", detail=reason, tool="IntentClassifier",
            elapsed_ms=(time.perf_counter() - t0) * 1000,
        ))
        logger.info("intent=%s request=%r", intent.value, request_text)

        if intent is Intent.COMPLEX_ORDER:
            return self._handle_complex_order(request_text, intent, trace)
        if intent is Intent.EXACT_MENU:
            return self._handle_exact_menu(request_text, intent, trace)
        if intent is Intent.PREFERENCE:
            return self._handle_preference(request_text, intent, trace)
        return self._handle_recommendation(request_text, intent, trace)

    def _handle_exact_menu(self, text: str, intent: Intent, trace: list[TraceStep]) -> AgentResponse:
        parsed_lines, group_size = self.parser.parse(text)
        if not parsed_lines:
            parsed_lines = [ParsedLine(raw_text=text, quantity=1)]
        items = [self._resolve_or_recommend(pl, trace) for pl in parsed_lines]
        items = self._apply_group_size(items, group_size)
        return self._build_response(text, intent, items, method="menu_lookup", confidence=0.97, trace=trace)

    def _handle_complex_order(self, text: str, intent: Intent, trace: list[TraceStep]) -> AgentResponse:
        parsed_lines, group_size = self.parser.parse(text)
        trace.append(TraceStep(
            step="split_order",
            detail=f"parsed into {len(parsed_lines)} line(s), group size {group_size}",
            tool="OrderParser",
        ))
        items = [self._resolve_or_recommend(pl, trace) for pl in parsed_lines]
        items = self._apply_group_size(items, group_size)
        return self._build_response(text, intent, items, method="smart_agent", confidence=0.90, trace=trace)

    def _handle_preference(self, text: str, intent: Intent, trace: list[TraceStep]) -> AgentResponse:
        t0 = time.perf_counter()
        filter_result = self.dietary_filter.filter_candidates(text)
        constraints_str = ", ".join(filter_result.matched_constraints) or 'none'
        trace.append(TraceStep(
            step="dietary_filter",
            detail=f"constraints matched: {constraints_str} -> {len(filter_result.candidate_names)} eligible item(s)",
            tool="DietaryFilter",
            elapsed_ms=(time.perf_counter() - t0) * 1000,
        ))
        line = ParsedLine(raw_text=text, quantity=1)
        item = self._resolve_or_recommend(line, trace, candidates=filter_result.candidate_names, skip_menu_lookup=True)
        return self._build_response(
            text, intent, [item], method="dietary_constrained_recommendation", confidence=0.88, trace=trace
        )

    def _handle_recommendation(self, text: str, intent: Intent, trace: list[TraceStep]) -> AgentResponse:
        line = ParsedLine(raw_text=text, quantity=1)
        item = self._resolve_or_recommend(line, trace, skip_menu_lookup=True)
        return self._build_response(text, intent, [item], method="llm_recommendation", confidence=0.82, trace=trace)

    def _resolve_or_recommend(
        self,
        parsed_line: ParsedLine,
        trace: list[TraceStep],
        candidates: list[str] | None = None,
        skip_menu_lookup: bool = False,
    ) -> ResolvedLineItem:
        if not skip_menu_lookup:
            t0 = time.perf_counter()
            resolved = self.estimator.resolve_from_menu(parsed_line)
            if resolved is not None:
                trace.append(TraceStep(
                    step="menu_lookup",
                    detail=f"'{parsed_line.raw_text}' -> {resolved.name} ({resolved.unit_time_min} min)",
                    tool="TimeEstimator",
                    elapsed_ms=(time.perf_counter() - t0) * 1000,
                ))
                return resolved

        candidate_names = candidates or self.menu.menu_names()
        t0 = time.perf_counter()
        recommended_name = self.llm.recommend_item(parsed_line.raw_text, candidate_names)
        trace.append(TraceStep(
            step="llm_recommendation",
            detail=f"no direct menu match for '{parsed_line.raw_text}' - {self.llm.name} suggested '{recommended_name}'",
            tool=self.llm.name,
            elapsed_ms=(time.perf_counter() - t0) * 1000,
        ))

        t0 = time.perf_counter()
        resolved = self.estimator.resolve_named_item(
            recommended_name,
            parsed_line.quantity,
            source="llm_recommendation",
            fallback_time_min=self.settings.unresolved_item_fallback_time_min,
        )
        trace.append(TraceStep(
            step="price_and_time",
            detail=f"'{resolved.name}' -> {resolved.unit_time_min} min, Rs {resolved.unit_price_inr}",
            tool="TimeEstimator",
            elapsed_ms=(time.perf_counter() - t0) * 1000,
        ))
        return resolved

    @staticmethod
    def _apply_group_size(items: list[ResolvedLineItem], group_size: int) -> list[ResolvedLineItem]:
        if group_size <= 1:
            return items
        for item in items:
            item.quantity *= group_size
            item.line_time_min = round(item.unit_time_min * item.quantity, 2)
            item.line_price_inr = round(item.unit_price_inr * item.quantity, 2)
        return items

    def _build_response(
        self,
        text: str,
        intent: Intent,
        items: list[ResolvedLineItem],
        method: str,
        confidence: float,
        trace: list[TraceStep],
    ) -> AgentResponse:
        total_time = round(sum(i.line_time_min for i in items) + self.settings.default_prep_buffer_min, 2)
        total_price = round(sum(i.line_price_inr for i in items), 2)
        return AgentResponse(
            request_text=text,
            intent=intent,
            items=items,
            total_time_min=total_time,
            total_price_inr=total_price,
            method=method,
            confidence=confidence,
            trace=trace,
        )
''')

print("Package written to:", PKG)

# ============================================================
# IMPORT + RUN
# ============================================================
import sys
sys.path.insert(0, str(ROOT))

# Reset any stale cached modules if you re-run this cell
for mod in list(sys.modules):
    if mod.startswith("coffee_agent"):
        del sys.modules[mod]

from coffee_agent import CoffeeAgent
from coffee_agent.config import Settings

# Fast, no-download mode. Switch llm_backend="local" to use flan-t5-base instead.
agent = CoffeeAgent(settings=Settings(llm_backend="rule_based"))

test_requests = [
    "latte, croissant",
    "2 lattes and a sandwich for 3 people",
    "something for someone who's lactose intolerant",
    "I'm tired, what should I get",
]

for req in test_requests:
    resp = agent.handle(req)
    print(f"\n>>> {req!r}")
    print(f"    intent={resp.intent.value}  method={resp.method}  confidence={resp.confidence}")
    print(f"    {resp.recommendation_summary}  |  {resp.total_time_min} min  |  Rs {resp.total_price_inr}")

# ============================================================
# CHAT-STYLE AGENT DASHBOARD — run after the setup cell above
# ============================================================
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML

INTENT_STYLES = {
    "exact_menu":     ("#F0F9FF", "#0369A1", "📋"),
    "complex_order":  ("#F0FDF4", "#15803D", "🧾"),
    "preference":     ("#FEF3F2", "#B42318", "🩺"),
    "recommendation": ("#F5F3FF", "#6D28D9", "🤖"),
}

SOURCE_STYLES = {
    "menu_lookup":       ("#F0F9FF", "#0369A1"),
    "llm_recommendation":("#F5F3FF", "#6D28D9"),
    "fallback":          ("#FEFCE8", "#854D0E"),
}

history = []  # keeps every AgentResponse this session, for the log panel

def render_trace_html(resp):
    rows = ""
    for step in resp.trace:
        rows += f"""
        <div style="padding:6px 10px;border-left:2px solid #ddd;margin-bottom:4px;">
            <span style="font-weight:500;">{step.tool}</span>
            <span style="color:#888;font-size:12px;"> · {step.elapsed_ms:.1f}ms</span><br>
            <span style="font-size:13px;color:#555;">{step.detail}</span>
        </div>"""
    return rows

def render_items_html(resp):
    rows = ""
    for item in resp.items:
        bg, fg = SOURCE_STYLES.get(item.source, ("#eee", "#333"))
        mods = ", ".join(item.modifiers) if item.modifiers else "—"
        rows += f"""
        <tr style="border-bottom:1px solid #eee;">
            <td style="padding:8px;font-weight:500;">{item.quantity}x {item.name.title()}</td>
            <td style="padding:8px;color:#666;font-size:12px;">{mods}</td>
            <td style="padding:8px;text-align:center;">{item.line_time_min} min</td>
            <td style="padding:8px;text-align:center;">Rs {item.line_price_inr}</td>
            <td style="padding:8px;text-align:center;">
                <span style="background:{bg};color:{fg};padding:2px 8px;border-radius:8px;font-size:11px;">{item.source}</span>
            </td>
        </tr>"""
    return rows

def render_response(resp):
    bg, fg, icon = INTENT_STYLES.get(resp.intent.value, ("#eee", "#333", "❓"))
    confidence_pct = int(resp.confidence * 100)

    return f"""
    <div style="border:1px solid #e5e7eb;border-radius:12px;padding:16px;margin-bottom:12px;">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;">
            <div>
                <span style="background:{bg};color:{fg};padding:4px 12px;border-radius:12px;font-size:12px;font-weight:500;">
                    {icon} {resp.intent.value.replace('_',' ')}
                </span>
                <span style="color:#888;font-size:12px;margin-left:8px;">via {resp.method}</span>
            </div>
            <span style="color:#888;font-size:12px;">confidence {confidence_pct}%</span>
        </div>
        <div style="font-style:italic;color:#555;margin-bottom:10px;">"{resp.request_text}"</div>
        <table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:10px;">
            <thead>
                <tr style="text-align:left;border-bottom:2px solid #333;">
                    <th style="padding:8px;">Item</th><th style="padding:8px;">Modifiers</th>
                    <th style="padding:8px;">Time</th><th style="padding:8px;">Price</th><th style="padding:8px;">Source</th>
                </tr>
            </thead>
            <tbody>{render_items_html(resp)}</tbody>
        </table>
        <div style="display:flex;justify-content:space-between;font-weight:500;margin-bottom:10px;">
            <span>⏱ Total time: {resp.total_time_min} min</span>
            <span>💰 Total: Rs {resp.total_price_inr}</span>
        </div>
        <details>
            <summary style="cursor:pointer;color:#888;font-size:12px;">Show reasoning trace ({len(resp.trace)} steps)</summary>
            <div style="margin-top:8px;">{render_trace_html(resp)}</div>
        </details>
    </div>"""

# ---------------- Widgets ----------------
query_input = widgets.Text(
    placeholder="e.g. 2 lattes for 3 people / something for someone lactose intolerant / I'm tired, what should I get",
    layout=widgets.Layout(width='75%')
)
ask_button = widgets.Button(description="Ask agent", button_style='success', icon='paper-plane')
backend_toggle = widgets.ToggleButtons(
    options=[('⚡ Rule-based (instant)', 'rule_based'), ('🤖 Local AI (flan-t5)', 'local')],
    description='Backend:'
)
clear_history_button = widgets.Button(description="Clear log", button_style='danger', layout=widgets.Layout(width='120px'))
output_area = widgets.Output()
log_area = widgets.Output()

current_agent = {"instance": agent}  # mutable box so the callback can swap backends

def switch_backend(change):
    new_backend = change['new']
    with output_area:
        print(f"Switching to {new_backend} backend...")
    current_agent["instance"] = CoffeeAgent(settings=Settings(llm_backend=new_backend))
    with output_area:
        clear_output(wait=True)
        print(f"✅ Now using: {current_agent['instance'].llm.name}")

backend_toggle.observe(switch_backend, names='value')

def on_ask_clicked(b):
    text = query_input.value.strip()
    if not text:
        return
    resp = current_agent["instance"].handle(text)
    history.append(resp)
    query_input.value = ''
    with output_area:
        clear_output(wait=True)
        display(HTML(render_response(resp)))
    render_log()

def on_clear_history(b):
    history.clear()
    render_log()

def render_log():
    with log_area:
        clear_output(wait=True)
        if not history:
            display(HTML("<p style='color:#888;'>No queries yet this session.</p>"))
            return
        rows = ""
        for i, r in enumerate(reversed(history), 1):
            bg, fg, icon = INTENT_STYLES.get(r.intent.value, ("#eee", "#333", "❓"))
            rows += f"""
            <div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #f0f0f0;font-size:13px;">
                <span>{icon} "{r.request_text}"</span>
                <span style="color:#888;">{r.recommendation_summary} · {r.total_time_min}min · Rs {r.total_price_inr}</span>
            </div>"""
        display(HTML(f"<div style='max-height:200px;overflow-y:auto;'>{rows}</div>"))

ask_button.on_click(on_ask_clicked)
clear_history_button.on_click(on_clear_history)
query_input.on_submit(lambda w: on_ask_clicked(None))  # Enter key also submits

# ---------------- Layout ----------------
header = widgets.HTML(value="""
    <h2 style='margin-bottom:2px;'>☕ Coffee Agent — Ask me anything</h2>
    <p style='color:#888;margin-top:2px;'>Order directly, ask for a recommendation, or state a dietary constraint.</p>
""")

log_header = widgets.HTML(value="<div style='font-weight:500;margin-top:16px;'>📜 Session log</div>")

display(widgets.VBox([
    header,
    backend_toggle,
    widgets.HBox([query_input, ask_button]),
    output_area,
    widgets.HBox([log_header, clear_history_button]),
    log_area
]))

render_log()

# ============================================================
#  Coffee AI Agent – Professional Version (July 2026)
#  Hybrid Agent: Deterministic Tools + LLM Reasoning
#  Compatible with:
#  !pip install langchain==0.1.0 langchain-core transformers torch pandas ipywidgets
# ============================================================

import json
import re
from typing import List, Dict, Optional, Set, Any
from dataclasses import dataclass, field
from enum import Enum

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML
import warnings
warnings.filterwarnings("ignore")

# ---------------------------------------------------------------
# 1. Menu Knowledge Base
# ---------------------------------------------------------------
@dataclass
class MenuItem:
    name: str
    time: float
    tags: Set[str] = field(default_factory=set)
    category: str = "beverage"

class MenuSystem:
    def __init__(self):
        self._items = {
            "espresso": MenuItem("espresso", 1.5, {"strong", "quick", "high-caffeine", "black"}),
            "double espresso": MenuItem("double espresso", 2.2, {"very-strong", "quick", "high-caffeine"}),
            "americano": MenuItem("americano", 2.0, {"strong", "black", "high-caffeine"}),
            "latte": MenuItem("latte", 3.0, {"milky", "mild", "creamy"}),
            "cappuccino": MenuItem("cappuccino", 3.0, {"milky", "foamy"}),
            "mocha": MenuItem("mocha", 3.5, {"sweet", "chocolate", "celebratory"}),
            "flat white": MenuItem("flat white", 3.0, {"milky", "smooth"}),
            "cold brew": MenuItem("cold brew", 1.0, {"cold", "strong", "smooth"}),
            "iced coffee": MenuItem("iced coffee", 1.5, {"cold", "refreshing"}),
            "matcha": MenuItem("matcha", 3.0, {"healthy", "green", "antioxidant"}),
            "green tea": MenuItem("green tea", 2.0, {"healthy", "light", "low-caffeine"}),
            "black tea": MenuItem("black tea", 2.0, {"healthy", "black"}),
            "hot chocolate": MenuItem("hot chocolate", 2.5, {"sweet", "comfort"}),
            "smoothie": MenuItem("smoothie", 4.0, {"cold", "sweet", "healthy-option"}),
            "croissant": MenuItem("croissant", 0.5, {"food", "pastry"}, "food"),
            "bagel": MenuItem("bagel", 1.5, {"food"}, "food"),
            "sandwich": MenuItem("sandwich", 4.0, {"food", "filling"}, "food"),
        }

        self.modifiers = {
            "large": 1.2, "extra large": 1.4, "xl": 1.4,
            "oat milk": 0.3, "almond milk": 0.3, "soy milk": 0.3,
            "extra hot": 0.5, "toasted": 0.5,
            "vanilla": 0.2, "caramel": 0.3, "whipped cream": 0.4,
            "double": 1.5, "extra shot": 0.8,
        }

    def all_items(self) -> List[MenuItem]:
        return list(self._items.values())

    def get(self, name: str) -> Optional[MenuItem]:
        return self._items.get(name.lower())

    def lookup(self, text: str) -> Optional[Dict]:
        text = text.lower().strip()
        for name, item in self._items.items():
            if name in text:
                time = item.time
                applied = []
                for mod, val in self.modifiers.items():
                    if mod in text:
                        if val >= 1.0:
                            time *= val
                        else:
                            time += val
                        applied.append(mod)
                return {
                    "item": name,
                    "time": round(time, 1),
                    "modifiers": applied,
                    "tags": item.tags
                }
        return None

# ---------------------------------------------------------------
# 2. Keyword → Tag mapping for preference scoring
# ---------------------------------------------------------------
_KEYWORD_TAGS = {
    "strong": {"strong", "high-caffeine", "very-strong"},
    "quick": {"quick"},
    "fast": {"quick"},
    "hurry": {"quick"},
    "tired": {"strong", "high-caffeine", "very-strong"},
    "sleep": {"strong", "high-caffeine"},
    "meeting": {"quick", "strong"},
    "cold": {"cold"},
    "iced": {"cold"},
    "sweet": {"sweet"},
    "chocolate": {"chocolate", "sweet"},
    "healthy": {"healthy", "green", "antioxidant", "low-caffeine"},
    "lactose": {"milky"},          # will be handled specially
    "vegan": {"milky"},
    "birthday": {"celebratory", "sweet", "chocolate"},
    "surprise": {"celebratory", "sweet"},
    "comfort": {"comfort", "sweet"},
    "refreshing": {"cold", "refreshing"},
}

# ---------------------------------------------------------------
# 3. Agent Response
# ---------------------------------------------------------------
@dataclass
class AgentResponse:
    recommendation: str
    estimated_time_min: float
    method: str
    reasoning: str
    confidence: float = 0.9

# ---------------------------------------------------------------
# 4. The Coffee AI Agent
# ---------------------------------------------------------------
class CoffeeAgent:
    def __init__(self, model_name: str = "google/flan-t5-base"):
        print("⏳ Loading local model (first run may take a minute)...")
        self.menu = MenuSystem()
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
        self.model_name = model_name
        print(f"✅ Model ready → {model_name}")

    def _generate(self, prompt: str, max_tokens: int = 40) -> str:
        inputs = self.tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)
        outputs = self.model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            do_sample=False,
            temperature=0.1
        )
        return self.tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

    # ---------- Deterministic Tools ----------
    def menu_lookup(self, text: str) -> Optional[Dict]:
        return self.menu.lookup(text)

    def split_order(self, text: str) -> List[str]:
        text = text.lower()
        m = re.search(r'for\s+(\d+)', text)
        group = int(m.group(1)) if m else 1
        text = re.sub(r'for\s+\d+.*', '', text)
        text = re.sub(r'\b(and|plus|with|also)\b', ',', text)
        parts = [p.strip() for p in text.split(',') if p.strip()]
        expanded = []
        for p in parts:
            q = re.match(r'(\d+)\s*(.+)', p)
            if q:
                expanded.extend([q.group(2).strip()] * int(q.group(1)))
            else:
                expanded.append(p)
        return expanded * max(1, group)

    # ---------- Fixed Recommendation Logic ----------
    def recommend_item(self, preference_text: str, candidate_items: Optional[List[str]] = None) -> str:
        text = preference_text.lower()
        wanted_tags: Set[str] = set()
        for keyword, tags in _KEYWORD_TAGS.items():
            if keyword in text:
                wanted_tags.update(tags)

        items = self.menu.all_items()
        if candidate_items:
            items = [i for i in items if i.name in candidate_items] or items

        if not wanted_tags:
            # default preference
            preferred = next((i for i in items if i.name == "latte"), None)
            return preferred.name if preferred else items[0].name

        def score(item: MenuItem) -> float:
            overlap = wanted_tags.intersection(item.tags)
            if not overlap:
                return 0.0
            # Jaccard-style: penalizes items with many unrelated tags
            return len(overlap) / len(set(item.tags) | wanted_tags)

        scored = [(score(i), i) for i in items]
        best_score = max(s for s, _ in scored)
        best_items = [i for s, i in scored if s == best_score]

        # Tie-break by specificity (fewest tags = more targeted)
        best_items.sort(key=lambda i: len(i.tags))
        return best_items[0].name

    def classify_intent(self, text: str) -> str:
        lower = text.lower()
        # Fast rule-based shortcuts first
        if any(w in lower for w in ["for ", "people", "colleagues", "of us", "x ", "×"]):
            return "complex_order"
        if any(w in lower for w in ["something", "surprise", "recommend", "suggest", "what should", "tired", "sleep", "hurry", "healthy", "birthday", "lactose", "vegan"]):
            return "preference"
        # Try exact match
        if self.menu.lookup(text):
            return "exact_menu"
        return "preference"

    # ---------- Main Agent Entry ----------
    def handle(self, request: str) -> AgentResponse:
        intent = self.classify_intent(request)
        steps = [f"Intent → {intent}"]

        # ----- Exact menu -----
        if intent == "exact_menu":
            items = [i.strip() for i in re.split(r',| and ', request) if i.strip()]
            total = 0.0
            names = []
            for item in items:
                found = self.menu_lookup(item)
                if found:
                    total += found["time"]
                    names.append(found["item"].title())
                    steps.append(f"Menu lookup → {found['item']} ({found['time']} min)")
                else:
                    rec = self.recommend_item(item)
                    found = self.menu_lookup(rec) or {"item": rec, "time": 2.5}
                    total += found["time"]
                    names.append(found["item"].title())
                    steps.append(f"Fallback reco → {found['item']}")
            return AgentResponse(
                recommendation=", ".join(names),
                estimated_time_min=round(total, 1),
                method="menu_lookup",
                reasoning="\n".join(steps),
                confidence=0.95
            )

        # ----- Complex / quantity -----
        if intent == "complex_order":
            parts = self.split_order(request)
            steps.append(f"Split → {parts}")
            total = 0.0
            names = []
            for p in parts:
                found = self.menu_lookup(p)
                if found:
                    total += found["time"]
                    names.append(found["item"].title())
                    steps.append(f"Menu → {found['item']} ({found['time']} min)")
                else:
                    rec = self.recommend_item(p)
                    found = self.menu_lookup(rec) or {"item": rec, "time": 2.5}
                    total += found["time"]
                    names.append(found["item"].title())
                    steps.append(f"AI reco → {found['item']}")
            return AgentResponse(
                recommendation=", ".join(names),
                estimated_time_min=round(total, 1),
                method="smart_agent",
                reasoning="\n".join(steps),
                confidence=0.90
            )

        # ----- Preference / recommendation -----
        rec_name = self.recommend_item(request)
        found = self.menu_lookup(rec_name) or {"item": rec_name, "time": 2.5}
        steps.append(f"Scored recommendation → {found['item']}")
        steps.append(f"Prep time → {found['time']} min")

        return AgentResponse(
            recommendation=found["item"].title(),
            estimated_time_min=found["time"],
            method="llm_recommendation",
            reasoning="\n".join(steps),
            confidence=0.87
        )

# ---------------------------------------------------------------
# 5. Professional UI
# ---------------------------------------------------------------
# ---------------------------------------------------------------
# 5. Professional UI (v2 — cleaner header, categorized examples)
# ---------------------------------------------------------------
agent = CoffeeAgent()

# --- Style helpers ---
def card(title: str, content: str, color: str = "#4F46E5") -> str:
    return f"""
    <div style="
        background: white;
        border-radius: 12px;
        padding: 16px 20px;
        margin: 8px 0;
        box-shadow: 0 1px 3px rgba(0,0,0,0.06);
        border: 1px solid #F0F0F0;
        border-left: 4px solid {color};
        font-family: 'Segoe UI', system-ui, sans-serif;
    ">
        <div style="font-size: 12px; color: #9CA3AF; text-transform: uppercase; letter-spacing: 0.04em; margin-bottom: 4px;">{title}</div>
        <div style="font-size: 18px; font-weight: 600; color: #111827;">{content}</div>
    </div>
    """

def method_badge(method: str) -> str:
    colors = {
        "menu_lookup": ("#EFF6FF", "#1E40AF"),
        "smart_agent": ("#EEF2FF", "#4338CA"),
        "llm_recommendation": ("#FDF2F8", "#9D174D"),
    }
    bg, fg = colors.get(method, ("#F3F4F6", "#374151"))
    return f"""
    <span style="
        background:{bg}; color:{fg};
        padding: 4px 12px; border-radius: 9999px;
        font-size: 12px; font-weight: 600;
    ">{method.replace('_', ' ').title()}</span>
    """

# --- Header: name + one line only ---
header = widgets.HTML("""
<div style="
    background: #111827;
    color: white;
    padding: 22px 28px;
    border-radius: 14px;
    margin-bottom: 18px;
    font-family: 'Segoe UI', system-ui, sans-serif;
">
    <h1 style="margin:0; font-size: 22px; font-weight: 600;">☕ Coffee AI Agent</h1>
    <p style="margin: 4px 0 0; opacity: 0.65; font-size: 14px;">
        Ask for a drink by name, describe a mood or need, or place an order for a group.
    </p>
</div>
""")

request_input = widgets.Textarea(
    value="",
    placeholder="e.g. 2 large oat milk lattes for 3 people, or 'something strong, I have a meeting in 10 minutes'",
    layout=widgets.Layout(width="100%", height="80px"),
    style={"description_width": "0px"}
)

run_button = widgets.Button(
    description="Ask the agent",
    button_style="primary",
    icon="paper-plane",
    layout=widgets.Layout(width="160px", height="38px")
)

clear_button = widgets.Button(
    description="Clear",
    layout=widgets.Layout(width="90px", height="38px")
)

output_area = widgets.Output()

# --- Examples grouped by category ---
example_groups = {
    "Exact orders": [
        "Latte",
        "Large mocha with oat milk",
        "Double espresso, extra hot",
        "Iced coffee with vanilla",
    ],
    "Group / multi-item orders": [
        "2 large oat milk lattes and a croissant for 3 people",
        "3 cappuccinos and a bagel",
        "A latte, a mocha, and a sandwich",
        "5x cold brew for the office",
    ],
    "Mood / situational": [
        "I have a meeting in 10 minutes, something strong but quick",
        "I didn't sleep well last night",
        "Something cold and sweet",
        "I'm in a hurry",
        "I need to relax after a long day",
    ],
    "Dietary & preference": [
        "I'm lactose intolerant",
        "Give me the healthiest option",
        "I don't like bitter coffee",
        "Something low calorie",
        "No caffeine for me please",
    ],
    "Open-ended": [
        "Surprise me",
        "Birthday coffee for my friend",
        "What do you recommend?",
    ],
}

def build_example_section(category: str, items: list) -> widgets.VBox:
    label = widgets.HTML(
        f"<div style='font-size:12px;font-weight:600;color:#6B7280;"
        f"text-transform:uppercase;letter-spacing:0.04em;margin:10px 0 6px;'>{category}</div>"
    )
    buttons = []
    for ex in items:
        btn = widgets.Button(
            description=ex[:46] + ("…" if len(ex) > 46 else ""),
            layout=widgets.Layout(width="auto", margin="2px", height="32px"),
            style={"button_color": "#F9FAFB"}
        )
        def make_handler(text):
            def handler(b):
                request_input.value = text
                on_run(None)
            return handler
        btn.on_click(make_handler(ex))
        buttons.append(btn)
    return widgets.VBox([label, widgets.HBox(buttons, layout=widgets.Layout(flex_flow="row wrap"))])

example_sections = [build_example_section(cat, items) for cat, items in example_groups.items()]

def on_run(b):
    with output_area:
        clear_output(wait=True)
        req = request_input.value.strip()
        if not req:
            display(HTML("<p style='color:#B45309'>Please enter a request.</p>"))
            return

        result = agent.handle(req)

        html = f"""
        <div style="font-family: 'Segoe UI', system-ui, sans-serif; max-width: 720px;">
            <div style="background:#F9FAFB; border-radius:12px; padding:14px 18px; margin-bottom:14px; border:1px solid #F0F0F0;">
                <div style="font-size:12px; color:#9CA3AF; text-transform:uppercase; letter-spacing:0.04em;">Request</div>
                <div style="font-size:15px; font-weight:500; margin-top:4px; color:#111827;">{req}</div>
            </div>

            {card("Recommendation", result.recommendation, "#4F46E5")}
            {card("Estimated prep time", f"{result.estimated_time_min} minutes", "#059669")}

            <div style="display:flex; gap:20px; margin:14px 4px; align-items:center;">
                <div>
                    <div style="font-size:11px; color:#9CA3AF; text-transform:uppercase; letter-spacing:0.04em; margin-bottom:4px;">Method</div>
                    {method_badge(result.method)}
                </div>
                <div>
                    <div style="font-size:11px; color:#9CA3AF; text-transform:uppercase; letter-spacing:0.04em; margin-bottom:4px;">Confidence</div>
                    <div style="font-weight:600; color:#111827;">{result.confidence:.0%}</div>
                </div>
            </div>

            <div style="
                background:#FAFAFA;
                border-radius:12px;
                padding:14px 18px;
                border:1px solid #EEE;
                margin-top:10px;
            ">
                <div style="font-size:12px; font-weight:600; color:#6B7280; text-transform:uppercase; letter-spacing:0.04em; margin-bottom:8px;">
                    Reasoning trace
                </div>
                <pre style="
                    margin:0;
                    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
                    font-size:12.5px;
                    white-space:pre-wrap;
                    color:#374151;
                ">{result.reasoning}</pre>
            </div>
        </div>
        """
        display(HTML(html))

def on_clear(b):
    request_input.value = ""
    with output_area:
        clear_output()

run_button.on_click(on_run)
clear_button.on_click(on_clear)

# --- Layout ---
ui = widgets.VBox(
    [header,
     widgets.HTML("<div style='font-weight:600; color:#111827; margin:4px 0 6px;'>Your request</div>"),
     request_input,
     widgets.HBox([run_button, clear_button], layout=widgets.Layout(margin="10px 0 4px")),
     widgets.HTML("<hr style='margin:18px 0 4px; border:none; border-top:1px solid #E5E7EB;'>"),
     widgets.HTML("<div style='font-weight:600; color:#111827; margin:6px 0 2px;'>Try an example</div>"),
     *example_sections,
     widgets.HTML("<hr style='margin:18px 0; border:none; border-top:1px solid #E5E7EB;'>"),
     output_area],
    layout=widgets.Layout(padding="8px", max_width="820px")
)

display(ui)

print("\n✅ Coffee AI Agent ready")
print("   Try an example above, or type your own request.")

# ============================================================
#  Coffee AI Agent – LLM-Driven Professional Version (July 2026)
#  Hybrid Agent: LLM makes every decision · Deterministic tools only do math
#  Compatible with:
#  !pip install langchain==0.1.0 langchain-core transformers torch pandas ipywidgets
# ============================================================

import json
import re
from typing import List, Dict, Optional, Set, Any
from dataclasses import dataclass, field
from enum import Enum

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML
import warnings
warnings.filterwarnings("ignore")

# ---------------------------------------------------------------
# 1. Menu Knowledge Base
# ---------------------------------------------------------------
@dataclass
class MenuItem:
    name: str
    time: float
    tags: Set[str] = field(default_factory=set)
    category: str = "beverage"

class MenuSystem:
    def __init__(self):
        self._items = {
            "espresso": MenuItem("espresso", 1.5, {"strong", "quick", "high-caffeine", "black"}),
            "double espresso": MenuItem("double espresso", 2.2, {"very-strong", "quick", "high-caffeine"}),
            "americano": MenuItem("americano", 2.0, {"strong", "black", "high-caffeine"}),
            "latte": MenuItem("latte", 3.0, {"milky", "mild", "creamy"}),
            "cappuccino": MenuItem("cappuccino", 3.0, {"milky", "foamy"}),
            "mocha": MenuItem("mocha", 3.5, {"sweet", "chocolate", "celebratory"}),
            "flat white": MenuItem("flat white", 3.0, {"milky", "smooth"}),
            "cold brew": MenuItem("cold brew", 1.0, {"cold", "strong", "smooth"}),
            "iced coffee": MenuItem("iced coffee", 1.5, {"cold", "refreshing"}),
            "matcha": MenuItem("matcha", 3.0, {"healthy", "green", "antioxidant"}),
            "green tea": MenuItem("green tea", 2.0, {"healthy", "light", "low-caffeine"}),
            "black tea": MenuItem("black tea", 2.0, {"healthy", "black"}),
            "hot chocolate": MenuItem("hot chocolate", 2.5, {"sweet", "comfort"}),
            "smoothie": MenuItem("smoothie", 4.0, {"cold", "sweet", "healthy-option"}),
            "croissant": MenuItem("croissant", 0.5, {"food", "pastry"}, "food"),
            "bagel": MenuItem("bagel", 1.5, {"food"}, "food"),
            "sandwich": MenuItem("sandwich", 4.0, {"food", "filling"}, "food"),
        }

        self.modifiers = {
            "large": 1.2, "extra large": 1.4, "xl": 1.4,
            "oat milk": 0.3, "almond milk": 0.3, "soy milk": 0.3,
            "extra hot": 0.5, "toasted": 0.5,
            "vanilla": 0.2, "caramel": 0.3, "whipped cream": 0.4,
            "double": 1.5, "extra shot": 0.8,
        }

    def all_items(self) -> List[MenuItem]:
        return list(self._items.values())

    def get(self, name: str) -> Optional[MenuItem]:
        return self._items.get(name.lower())

    def lookup(self, text: str) -> Optional[Dict]:
        text = text.lower().strip()
        for name, item in self._items.items():
            if name in text:
                time = item.time
                applied = []
                for mod, val in self.modifiers.items():
                    if mod in text:
                        if val >= 1.0:
                            time *= val
                        else:
                            time += val
                        applied.append(mod)
                return {
                    "item": name,
                    "time": round(time, 1),
                    "modifiers": applied,
                    "tags": item.tags
                }
        return None

# ---------------------------------------------------------------
# 2. Agent Response
# ---------------------------------------------------------------
@dataclass
class AgentResponse:
    recommendation: str
    estimated_time_min: float
    method: str
    reasoning: str
    confidence: float = 0.9

# ---------------------------------------------------------------
# 3. The Coffee AI Agent — LLM actually drives every decision
# ---------------------------------------------------------------
class CoffeeAgent:
    def __init__(self, model_name: str = "google/flan-t5-base"):
        print("⏳ Loading local model (first run may take a minute)...")
        self.menu = MenuSystem()
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
        self.model_name = model_name
        print(f"✅ Model ready → {model_name}")

    def _generate(self, prompt: str, max_tokens: int = 60) -> str:
        inputs = self.tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)
        outputs = self.model.generate(
            **inputs, max_new_tokens=max_tokens, do_sample=False, temperature=0.1
        )
        return self.tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

    # ---------- Deterministic tool: only computes numbers, never decides *what* ----------
    def price_and_time(self, item_name: str, modifiers_text: str = "") -> Dict:
        """Given a known menu item name (decided by the LLM), compute exact
        time/price. This is the one place raw arithmetic happens — the model
        is not asked to do math, since small LLMs are unreliable at it."""
        item = self.menu.get(item_name.lower().strip())
        if item is None:
            return {"item": item_name, "time": 2.5, "modifiers": []}
        time = item.time
        applied = []
        text = modifiers_text.lower()
        for mod, val in self.menu.modifiers.items():
            if mod in text:
                time = time * val if val >= 1.0 else time + val
                applied.append(mod)
        return {"item": item.name, "time": round(time, 1), "modifiers": applied}

    # ---------- LLM tool 1: intent classification ----------
    def classify_intent(self, text: str) -> str:
        prompt = (
            "Classify this coffee shop customer request into exactly one category:\n"
            "- exact_menu: names one specific drink/food clearly\n"
            "- complex_order: multiple items, a quantity, or a group of people\n"
            "- preference: mentions a diet, health, or allergy constraint\n"
            "- recommendation: vague mood, feeling, or open-ended ask, no specific item named\n\n"
            f'Request: "{text}"\n'
            "Answer with only the category name."
        )
        raw = self._generate(prompt, max_tokens=8).lower()
        for label in ["exact_menu", "complex_order", "preference", "recommendation"]:
            if label.replace("_", " ") in raw or label in raw:
                return label
        return "recommendation"  # only reached if the model output was unparseable

    # ---------- LLM tool 2: extract items from a (possibly multi-item) order ----------
    def extract_items(self, text: str) -> List[Dict]:
        menu_names = ", ".join(sorted(self.menu._items.keys()))
        prompt = (
            f"Menu items available: {menu_names}\n\n"
            f'Customer said: "{text}"\n'
            "List every menu item they want, one per line, as: quantity | item name | modifiers\n"
            "If a group size is mentioned (e.g. 'for 4 people'), multiply quantities accordingly.\n"
            "Example output:\n2 | latte | oat milk, extra hot\n1 | croissant | toasted"
        )
        raw = self._generate(prompt, max_tokens=80)
        lines = [l.strip() for l in raw.split("\n") if "|" in l]
        parsed = []
        for line in lines:
            parts = [p.strip() for p in line.split("|")]
            if len(parts) >= 2:
                qty = int(parts[0]) if parts[0].isdigit() else 1
                item_name = parts[1]
                mods = parts[2] if len(parts) > 2 else ""
                parsed.append({"quantity": qty, "item": item_name, "modifiers": mods})
        return parsed

    # ---------- LLM tool 3: open-ended recommendation ----------
    def recommend_item(self, preference_text: str, candidate_items: Optional[List[str]] = None) -> str:
        names = candidate_items or list(self.menu._items.keys())
        prompt = (
            f'A customer said: "{preference_text}"\n'
            f"Menu options: {', '.join(names)}.\n"
            "Reply with ONLY the single best matching item name, nothing else."
        )
        raw = self._generate(prompt, max_tokens=12).lower().strip()
        for name in sorted(names, key=len, reverse=True):
            if name in raw:
                return name
        return names[0]  # model output didn't match anything on the menu

    # ---------- LLM tool 4: dietary/preference filtering ----------
    def filter_by_constraint(self, text: str) -> List[str]:
        all_items = list(self.menu._items.keys())
        prompt = (
            f'Customer constraint: "{text}"\n'
            f"Full menu: {', '.join(all_items)}\n"
            "List ONLY the menu items that are safe/suitable for this constraint, "
            "comma-separated, nothing else."
        )
        raw = self._generate(prompt, max_tokens=60).lower()
        matched = [name for name in all_items if name in raw]
        return matched if matched else all_items  # constraint too strict/unparsed – don't empty the menu

    # ---------- Main agent entry point ----------
    def handle(self, request: str) -> AgentResponse:
        steps = []
        intent = self.classify_intent(request)
        steps.append(f"LLM classified intent → {intent}")

        if intent == "exact_menu":
            extracted = self.extract_items(request)
            steps.append(f"LLM extracted items → {extracted}")
            if not extracted:
                extracted = [{"quantity": 1, "item": request, "modifiers": ""}]
            total, names = 0.0, []
            for e in extracted:
                result = self.price_and_time(e["item"], e["modifiers"])
                total += result["time"] * e["quantity"]
                names.append(f"{e['quantity']}x {result['item'].title()}")
                steps.append(f"Priced → {result['item']} ({result['time']} min × {e['quantity']})")
            return AgentResponse(", ".join(names), round(total, 1), "menu_lookup",
                                  "\n".join(steps), confidence=0.93)

        if intent == "complex_order":
            extracted = self.extract_items(request)
            steps.append(f"LLM extracted items → {extracted}")
            total, names = 0.0, []
            for e in extracted:
                result = self.price_and_time(e["item"], e["modifiers"])
                total += result["time"] * e["quantity"]
                names.append(f"{e['quantity']}x {result['item'].title()}")
                steps.append(f"Priced → {result['item']} ({result['time']} min × {e['quantity']})")
            if not extracted:
                steps.append("LLM extraction returned nothing usable — falling back to single-item read")
                rec = self.recommend_item(request)
                result = self.price_and_time(rec)
                names, total = [result["item"].title()], result["time"]
            return AgentResponse(", ".join(names), round(total, 1), "smart_agent",
                                  "\n".join(steps), confidence=0.87)

        if intent == "preference":
            candidates = self.filter_by_constraint(request)
            steps.append(f"LLM filtered candidates → {candidates}")
            rec = self.recommend_item(request, candidates)
            result = self.price_and_time(rec)
            steps.append(f"LLM recommended → {result['item']} ({result['time']} min)")
            return AgentResponse(result["item"].title(), result["time"], "llm_recommendation",
                                  "\n".join(steps), confidence=0.85)

        # recommendation (fully open-ended)
        rec = self.recommend_item(request)
        result = self.price_and_time(rec)
        steps.append(f"LLM recommended → {result['item']} ({result['time']} min)")
        return AgentResponse(result["item"].title(), result["time"], "llm_recommendation",
                              "\n".join(steps), confidence=0.82)

# ---------------------------------------------------------------
# 4. Professional UI
# ---------------------------------------------------------------
agent = CoffeeAgent()

# --- Style helpers ---
def card(title: str, content: str, color: str = "#4F46E5") -> str:
    return f"""
    <div style="
        background: white;
        border-radius: 12px;
        padding: 16px 20px;
        margin: 8px 0;
        box-shadow: 0 1px 3px rgba(0,0,0,0.06);
        border: 1px solid #F0F0F0;
        border-left: 4px solid {color};
        font-family: 'Segoe UI', system-ui, sans-serif;
    ">
        <div style="font-size: 12px; color: #9CA3AF; text-transform: uppercase; letter-spacing: 0.04em; margin-bottom: 4px;">{title}</div>
        <div style="font-size: 18px; font-weight: 600; color: #111827;">{content}</div>
    </div>
    """

def method_badge(method: str) -> str:
    colors = {
        "menu_lookup": ("#EFF6FF", "#1E40AF"),
        "smart_agent": ("#EEF2FF", "#4338CA"),
        "llm_recommendation": ("#FDF2F8", "#9D174D"),
    }
    bg, fg = colors.get(method, ("#F3F4F6", "#374151"))
    return f"""
    <span style="
        background:{bg}; color:{fg};
        padding: 4px 12px; border-radius: 9999px;
        font-size: 12px; font-weight: 600;
    ">{method.replace('_', ' ').title()}</span>
    """

# --- Header ---
header = widgets.HTML("""
<div style="
    background: #111827;
    color: white;
    padding: 22px 28px;
    border-radius: 14px;
    margin-bottom: 18px;
    font-family: 'Segoe UI', system-ui, sans-serif;
">
    <h1 style="margin:0; font-size: 22px; font-weight: 600;">☕ Coffee AI Agent</h1>
    <p style="margin: 4px 0 0; opacity: 0.65; font-size: 14px;">
        Ask for a drink by name, describe a mood or need, or place an order for a group.
    </p>
</div>
""")

request_input = widgets.Textarea(
    value="",
    placeholder="e.g. 2 large oat milk lattes for 3 people, or 'something strong, I have a meeting in 10 minutes'",
    layout=widgets.Layout(width="100%", height="80px"),
    style={"description_width": "0px"}
)

run_button = widgets.Button(
    description="Ask the agent",
    button_style="primary",
    icon="paper-plane",
    layout=widgets.Layout(width="160px", height="38px")
)

clear_button = widgets.Button(
    description="Clear",
    layout=widgets.Layout(width="90px", height="38px")
)

output_area = widgets.Output()

# --- Examples grouped by category ---
example_groups = {
    "Exact orders": [
        "Latte",
        "Large mocha with oat milk",
        "Double espresso, extra hot",
        "Iced coffee with vanilla",
    ],
    "Group / multi-item orders": [
        "2 large oat milk lattes and a croissant for 3 people",
        "3 cappuccinos and a bagel",
        "A latte, a mocha, and a sandwich",
        "5x cold brew for the office",
    ],
    "Mood / situational": [
        "I have a meeting in 10 minutes, something strong but quick",
        "I didn't sleep well last night",
        "Something cold and sweet",
        "I'm in a hurry",
        "I need to relax after a long day",
    ],
    "Dietary & preference": [
        "I'm lactose intolerant",
        "Give me the healthiest option",
        "I don't like bitter coffee",
        "Something low calorie",
        "No caffeine for me please",
    ],
    "Open-ended": [
        "Surprise me",
        "Birthday coffee for my friend",
        "What do you recommend?",
    ],
}

def build_example_section(category: str, items: list) -> widgets.VBox:
    label = widgets.HTML(
        f"<div style='font-size:12px;font-weight:600;color:#6B7280;"
        f"text-transform:uppercase;letter-spacing:0.04em;margin:10px 0 6px;'>{category}</div>"
    )
    buttons = []
    for ex in items:
        btn = widgets.Button(
            description=ex[:46] + ("…" if len(ex) > 46 else ""),
            layout=widgets.Layout(width="auto", margin="2px", height="32px"),
            style={"button_color": "#F9FAFB"}
        )
        def make_handler(text):
            def handler(b):
                request_input.value = text
                on_run(None)
            return handler
        btn.on_click(make_handler(ex))
        buttons.append(btn)
    return widgets.VBox([label, widgets.HBox(buttons, layout=widgets.Layout(flex_flow="row wrap"))])

example_sections = [build_example_section(cat, items) for cat, items in example_groups.items()]

def on_run(b):
    with output_area:
        clear_output(wait=True)
        req = request_input.value.strip()
        if not req:
            display(HTML("<p style='color:#B45309'>Please enter a request.</p>"))
            return

        result = agent.handle(req)

        html = f"""
        <div style="font-family: 'Segoe UI', system-ui, sans-serif; max-width: 720px;">
            <div style="background:#F9FAFB; border-radius:12px; padding:14px 18px; margin-bottom:14px; border:1px solid #F0F0F0;">
                <div style="font-size:12px; color:#9CA3AF; text-transform:uppercase; letter-spacing:0.04em;">Request</div>
                <div style="font-size:15px; font-weight:500; margin-top:4px; color:#111827;">{req}</div>
            </div>

            {card("Recommendation", result.recommendation, "#4F46E5")}
            {card("Estimated prep time", f"{result.estimated_time_min} minutes", "#059669")}

            <div style="display:flex; gap:20px; margin:14px 4px; align-items:center;">
                <div>
                    <div style="font-size:11px; color:#9CA3AF; text-transform:uppercase; letter-spacing:0.04em; margin-bottom:4px;">Method</div>
                    {method_badge(result.method)}
                </div>
                <div>
                    <div style="font-size:11px; color:#9CA3AF; text-transform:uppercase; letter-spacing:0.04em; margin-bottom:4px;">Confidence</div>
                    <div style="font-weight:600; color:#111827;">{result.confidence:.0%}</div>
                </div>
            </div>

            <div style="
                background:#FAFAFA;
                border-radius:12px;
                padding:14px 18px;
                border:1px solid #EEE;
                margin-top:10px;
            ">
                <div style="font-size:12px; font-weight:600; color:#6B7280; text-transform:uppercase; letter-spacing:0.04em; margin-bottom:8px;">
                    Reasoning trace
                </div>
                <pre style="
                    margin:0;
                    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
                    font-size:12.5px;
                    white-space:pre-wrap;
                    color:#374151;
                ">{result.reasoning}</pre>
            </div>
        </div>
        """
        display(HTML(html))

def on_clear(b):
    request_input.value = ""
    with output_area:
        clear_output()

run_button.on_click(on_run)
clear_button.on_click(on_clear)

# --- Layout ---
ui = widgets.VBox(
    [header,
     widgets.HTML("<div style='font-weight:600; color:#111827; margin:4px 0 6px;'>Your request</div>"),
     request_input,
     widgets.HBox([run_button, clear_button], layout=widgets.Layout(margin="10px 0 4px")),
     widgets.HTML("<hr style='margin:18px 0 4px; border:none; border-top:1px solid #E5E7EB;'>"),
     widgets.HTML("<div style='font-weight:600; color:#111827; margin:6px 0 2px;'>Try an example</div>"),
     *example_sections,
     widgets.HTML("<hr style='margin:18px 0; border:none; border-top:1px solid #E5E7EB;'>"),
     output_area],
    layout=widgets.Layout(padding="8px", max_width="820px")
)

display(ui)

print("\n✅ Coffee AI Agent ready")
print("   Try an example above, or type your own request.")